// All config types are derived from the Zod schema — re-exported here for backward compat
export type {
  HermexConfig,
  HermexConfigInput,
  RuleSeverity,
  RuleConfig,
  PackageFieldRule,
  EngineVersionRule,
  CodeownersRule,
  PackagesConfig,
  VersusConfig,
  RulesConfig,
  OverrideConfig,
  OverrideRuleSeverity,
  OverrideRuleConfig,
  OverridePackageFieldRule,
  OverrideEngineVersionRule,
  OverrideCodeownersRule,
  OutputConfig,
  ReleaseAgeConfig,
  ReleaseAgeThresholds,
} from './schema';
